/* The following code was generated by JFlex 1.3.5 on 10/6/17 9:58 PM */

package pasito.syntax;
import java_cup.runtime.ComplexSymbolFactory;
import java_cup.runtime.ComplexSymbolFactory.Location;
import java_cup.runtime.Symbol;
import java.lang.*;
import java.io.InputStreamReader;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.3.5
 * on 10/6/17 9:58 PM from the specification file
 * <tt>file:/C:/Users/Andre/Documents/UFS/LFT/Pasito_Prof/MeuPasito/lexer.jflex</tt>
 */
public class Lexer implements sym, java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  final public static int YYEOF = -1;

  /** initial size of the lookahead buffer */
  final private static int YY_BUFFERSIZE = 16384;

  /** lexical states */
  final public static int CODESEG = 1;
  final public static int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  final private static String yycmap_packed = 
    "\11\0\1\3\1\1\1\0\1\3\1\1\22\0\1\3\1\32\4\0"+
    "\1\31\1\0\1\37\1\40\1\5\1\30\1\47\1\20\1\17\1\4"+
    "\1\7\11\7\1\46\1\50\1\41\1\36\3\0\4\6\1\10\1\24"+
    "\15\6\1\21\6\6\1\42\1\0\1\43\3\0\1\25\1\51\1\56"+
    "\1\55\1\15\1\53\1\62\1\61\1\52\2\6\1\26\1\6\1\14"+
    "\1\13\1\12\1\6\1\22\1\27\1\16\1\23\1\54\1\60\1\11"+
    "\1\57\1\6\1\44\1\2\1\45\144\0\1\33\u1f56\0\1\35\162\0"+
    "\1\34\udf53\0";

  /** 
   * Translates characters to character classes
   */
  final private static char [] yycmap = yy_unpack_cmap(yycmap_packed);

  /** 
   * Translates a state to a row index in the transition table
   */
  final private static int yy_rowMap [] = { 
        0,    51,   102,   102,   153,   204,   102,   153,   255,   306, 
      357,   408,   102,   459,   510,   561,   612,   102,   663,   102, 
      714,   102,   102,   102,   102,   102,   102,   102,   102,   765, 
      102,   102,   816,   867,   918,   969,  1020,  1071,  1122,  1173, 
     1224,  1275,  1326,  1377,  1428,  1479,  1530,  1581,  1632,  1683, 
     1734,   102,  1785,   102,  1836,  1887,   153,  1938,  1989,  2040, 
     2091,  2142,  2193,  2244,  2295,  2346,  2397,  2448,  2499,  2550, 
     2601,   102,  2652,  2703,  2754,  2805,  2856,  2907,  2958,  3009, 
      153,  3060,  3111,  3162,   153,  3213,  3264,  3315,  3366,  3417, 
     3417,   153,   153,   153,   153,  3468,  3519,  3570,  3621,   153, 
     3672,   153,  3723,  3774,  3825,  3876,  3927,   153,  3978,  4029, 
     4080,  4131,   102,  4182,  4233,   153,   153,  4284,   153,  4335, 
      153,   153,   153,  4386,  4437,  4488,  4539,  4590,  4641,   153, 
     4692,  4743,  4794,   102,   153,  4845,  4896,   153
  };

  /** 
   * The packed transition table of the DFA (part 0)
   */
  final private static String yy_packed0 = 
    "\1\3\1\4\1\5\1\4\1\6\1\7\1\10\1\11"+
    "\5\10\1\12\1\13\1\14\1\15\1\16\1\17\1\10"+
    "\1\20\2\10\1\21\1\22\1\23\1\24\1\25\2\3"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\1\36\1\37\1\40\1\41\1\42\1\43\1\44\1\45"+
    "\1\46\4\10\63\3\65\0\1\10\3\0\11\10\2\0"+
    "\7\10\21\0\12\10\4\0\1\47\1\50\64\0\1\11"+
    "\1\51\6\0\1\52\45\0\1\10\3\0\11\10\2\0"+
    "\5\10\1\53\1\10\21\0\12\10\2\0\1\10\3\0"+
    "\11\10\2\0\1\10\1\54\5\10\21\0\6\10\1\55"+
    "\3\10\7\0\1\52\7\0\1\56\45\0\1\10\3\0"+
    "\11\10\2\0\1\10\1\57\5\10\21\0\12\10\2\0"+
    "\1\10\3\0\7\10\1\60\1\10\2\0\7\10\21\0"+
    "\12\10\2\0\1\10\3\0\11\10\2\0\4\10\1\61"+
    "\2\10\21\0\12\10\2\0\1\10\3\0\10\10\1\62"+
    "\2\0\7\10\21\0\7\10\1\63\2\10\31\0\1\64"+
    "\65\0\1\65\64\0\1\66\26\0\1\10\3\0\5\10"+
    "\1\67\3\10\2\0\7\10\21\0\12\10\2\0\1\10"+
    "\3\0\6\10\1\70\2\10\2\0\7\10\21\0\2\10"+
    "\1\71\7\10\2\0\1\10\3\0\5\10\1\72\3\10"+
    "\2\0\2\10\1\73\1\10\1\74\1\75\1\10\21\0"+
    "\12\10\2\0\1\10\3\0\11\10\2\0\4\10\1\76"+
    "\2\10\21\0\12\10\2\0\1\10\3\0\7\10\1\77"+
    "\1\10\2\0\7\10\21\0\12\10\2\0\1\10\3\0"+
    "\5\10\1\100\3\10\2\0\4\10\1\101\2\10\21\0"+
    "\12\10\1\47\1\4\61\47\5\50\1\102\55\50\11\0"+
    "\1\103\60\0\1\52\1\104\4\0\1\104\47\0\1\10"+
    "\3\0\11\10\2\0\6\10\1\105\21\0\12\10\2\0"+
    "\1\10\3\0\11\10\2\0\2\10\1\106\4\10\21\0"+
    "\12\10\2\0\1\10\3\0\4\10\1\107\4\10\2\0"+
    "\7\10\21\0\12\10\17\0\1\110\45\0\1\10\3\0"+
    "\11\10\2\0\2\10\1\111\4\10\21\0\12\10\2\0"+
    "\1\10\3\0\10\10\1\112\2\0\7\10\21\0\12\10"+
    "\2\0\1\10\3\0\11\10\2\0\5\10\1\113\1\10"+
    "\21\0\12\10\2\0\1\10\3\0\11\10\2\0\1\10"+
    "\1\114\5\10\21\0\12\10\2\0\1\10\3\0\11\10"+
    "\2\0\7\10\21\0\1\10\1\115\10\10\35\0\1\116"+
    "\27\0\1\10\3\0\5\10\1\117\3\10\2\0\7\10"+
    "\21\0\12\10\2\0\1\10\3\0\10\10\1\120\2\0"+
    "\7\10\21\0\12\10\2\0\1\10\3\0\11\10\2\0"+
    "\1\10\1\121\5\10\21\0\12\10\2\0\1\10\3\0"+
    "\6\10\1\122\2\10\2\0\7\10\21\0\12\10\2\0"+
    "\1\10\3\0\11\10\2\0\5\10\1\123\1\10\21\0"+
    "\12\10\2\0\1\10\3\0\5\10\1\124\3\10\2\0"+
    "\7\10\21\0\12\10\2\0\1\10\3\0\11\10\2\0"+
    "\1\10\1\125\5\10\21\0\12\10\2\0\1\10\3\0"+
    "\11\10\2\0\7\10\21\0\2\10\1\126\7\10\2\0"+
    "\1\10\3\0\6\10\1\127\2\10\2\0\7\10\21\0"+
    "\12\10\2\0\1\10\3\0\11\10\2\0\6\10\1\130"+
    "\21\0\12\10\4\50\1\4\1\102\55\50\12\0\1\131"+
    "\57\0\1\132\10\0\1\133\7\0\1\133\34\0\1\10"+
    "\3\0\7\10\1\134\1\10\2\0\7\10\21\0\12\10"+
    "\2\0\1\10\3\0\7\10\1\135\1\10\2\0\7\10"+
    "\21\0\12\10\2\0\1\10\3\0\7\10\1\136\1\10"+
    "\2\0\7\10\21\0\12\10\2\0\1\10\3\0\7\10"+
    "\1\137\1\10\2\0\7\10\21\0\12\10\2\0\1\10"+
    "\3\0\11\10\2\0\2\10\1\140\4\10\21\0\12\10"+
    "\2\0\1\10\3\0\11\10\2\0\6\10\1\111\21\0"+
    "\12\10\2\0\1\10\3\0\11\10\2\0\2\10\1\141"+
    "\4\10\21\0\12\10\2\0\1\10\3\0\10\10\1\142"+
    "\2\0\7\10\21\0\12\10\36\0\1\143\26\0\1\10"+
    "\3\0\11\10\2\0\5\10\1\144\1\10\21\0\12\10"+
    "\2\0\1\10\3\0\7\10\1\145\1\10\2\0\7\10"+
    "\21\0\12\10\2\0\1\10\3\0\11\10\2\0\7\10"+
    "\21\0\5\10\1\146\4\10\2\0\1\10\3\0\11\10"+
    "\2\0\5\10\1\147\1\150\21\0\12\10\2\0\1\10"+
    "\3\0\11\10\2\0\4\10\1\151\2\10\21\0\12\10"+
    "\2\0\1\10\3\0\11\10\2\0\4\10\1\152\2\10"+
    "\21\0\12\10\2\0\1\10\3\0\11\10\2\0\6\10"+
    "\1\153\21\0\12\10\2\0\1\10\3\0\7\10\1\154"+
    "\1\10\2\0\7\10\21\0\12\10\13\0\1\155\56\0"+
    "\1\132\55\0\1\10\3\0\11\10\2\0\1\10\1\156"+
    "\5\10\21\0\12\10\2\0\1\10\3\0\11\10\2\0"+
    "\7\10\21\0\5\10\1\157\4\10\2\0\1\10\3\0"+
    "\11\10\2\0\7\10\21\0\5\10\1\160\4\10\36\0"+
    "\1\161\26\0\1\10\3\0\11\10\2\0\1\10\1\162"+
    "\5\10\21\0\12\10\2\0\1\10\3\0\10\10\1\163"+
    "\2\0\7\10\21\0\12\10\2\0\1\10\3\0\7\10"+
    "\1\164\1\10\2\0\7\10\21\0\12\10\2\0\1\10"+
    "\3\0\10\10\1\165\2\0\7\10\21\0\12\10\2\0"+
    "\1\10\3\0\11\10\2\0\2\10\1\166\4\10\21\0"+
    "\12\10\2\0\1\10\3\0\10\10\1\167\2\0\7\10"+
    "\21\0\12\10\14\0\1\170\50\0\1\10\3\0\6\10"+
    "\1\171\2\10\2\0\7\10\21\0\12\10\2\0\1\10"+
    "\3\0\10\10\1\172\2\0\7\10\21\0\12\10\2\0"+
    "\1\10\3\0\11\10\2\0\7\10\21\0\10\10\1\173"+
    "\1\10\2\0\1\10\3\0\11\10\2\0\7\10\21\0"+
    "\2\10\1\174\7\10\2\0\1\10\3\0\11\10\2\0"+
    "\7\10\21\0\10\10\1\175\1\10\2\0\1\10\3\0"+
    "\11\10\2\0\5\10\1\176\1\10\21\0\12\10\15\0"+
    "\1\177\47\0\1\10\3\0\11\10\2\0\4\10\1\200"+
    "\2\10\21\0\12\10\2\0\1\10\3\0\11\10\2\0"+
    "\1\10\1\201\5\10\21\0\12\10\2\0\1\10\3\0"+
    "\10\10\1\202\2\0\7\10\21\0\12\10\14\0\1\203"+
    "\50\0\1\10\3\0\11\10\2\0\7\10\21\0\5\10"+
    "\1\204\4\10\2\0\1\10\3\0\5\10\1\205\3\10"+
    "\2\0\7\10\21\0\12\10\16\0\1\206\46\0\1\10"+
    "\3\0\7\10\1\207\1\10\2\0\7\10\21\0\12\10"+
    "\2\0\1\10\3\0\11\10\2\0\2\10\1\210\4\10"+
    "\21\0\12\10\2\0\1\10\3\0\11\10\2\0\7\10"+
    "\21\0\11\10\1\211\2\0\1\10\3\0\11\10\2\0"+
    "\7\10\21\0\10\10\1\212\1\10";

  /** 
   * The transition table of the DFA
   */
  final private static int yytrans [] = yy_unpack();


  /* error codes */
  final private static int YY_UNKNOWN_ERROR = 0;
  final private static int YY_ILLEGAL_STATE = 1;
  final private static int YY_NO_MATCH = 2;
  final private static int YY_PUSHBACK_2BIG = 3;

  /* error messages for the codes above */
  final private static String YY_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Internal error: unknown state",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * YY_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private final static byte YY_ATTRIBUTE[] = {
     0,  0,  9,  9,  1,  1,  9,  1,  1,  1,  1,  1,  9,  1,  1,  1, 
     1,  9,  1,  9,  1,  9,  9,  9,  9,  9,  9,  9,  9,  1,  9,  9, 
     1,  1,  1,  1,  1,  1,  1,  0,  0,  1,  1,  1,  1,  0,  1,  1, 
     1,  1,  1,  9,  0,  9,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  0,  0,  0,  1,  1,  1,  9,  1,  1,  1,  1,  1,  0,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  0,  1,  0,  1,  1,  1,  1,  1, 
     1,  1,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  0,  1,  1,  1, 
     9,  1,  1,  1,  1,  1,  1,  0,  1,  1,  1,  1,  1,  1,  0,  1, 
     1,  1,  1,  1,  1,  9,  1,  1,  1,  1
  };

  /** the input device */
  private java.io.Reader yy_reader;

  /** the current state of the DFA */
  private int yy_state;

  /** the current lexical state */
  private int yy_lexical_state = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char yy_buffer[] = new char[YY_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int yy_markedPos;

  /** the textposition at the last state to be included in yytext */
  private int yy_pushbackPos;

  /** the current text position in the buffer */
  private int yy_currentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int yy_startRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int yy_endRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn; 

  /** 
   * yy_atBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean yy_atBOL = true;

  /** yy_atEOF == true <=> the scanner is at the EOF */
  private boolean yy_atEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean yy_eof_done;

  /* user code: */
	public Lexer(ComplexSymbolFactory sf, java.io.InputStream is){
		this(is);
        symbolFactory = sf;
    }
	public Lexer(ComplexSymbolFactory sf, java.io.Reader reader){
		this(reader);
        symbolFactory = sf;
    }
    
    private StringBuffer sb;
    private ComplexSymbolFactory symbolFactory;
    private int csline,cscolumn;

    public Symbol symbol(String name, int code){
        System.out.println("<" + name + ", " + yytext() + "> (Linha = " + yyline + "; Coluna = " + yycolumn + ")");
    
		return symbolFactory.newSymbol(name, code,
						new Location(yyline+1,yycolumn+1, yychar), // -yylength()
						new Location(yyline+1,yycolumn+yylength(), yychar+yylength())
				);
    }
    
    private Symbol symbol(String name, int sym, Object val) {
            System.out.println("<" + name + ", " + yytext() + "> (" + yyline + " - " + yycolumn + ")");
            
            Location left = new Location(yyline+1,yycolumn+1,yychar);
            Location right= new Location(yyline+1,yycolumn+yylength(), yychar+yylength());
        
            return symbolFactory.newSymbol(name, sym, left, right,val);
    }
    
    protected void emit_warning(String message){
    	System.out.println("scanner warning: " + message + " at : 2 "+ 
    			(yyline+1) + " " + (yycolumn+1) + " " + yychar);
    }
    
    protected void emit_error(String message){
    	System.out.println("scanner error: " + message + " at : 2" + 
    			(yyline+1) + " " + (yycolumn+1) + " " + yychar);
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.yy_reader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the split, compressed DFA transition table.
   *
   * @return the unpacked transition table
   */
  private static int [] yy_unpack() {
    int [] trans = new int[4947];
    int offset = 0;
    offset = yy_unpack(yy_packed0, offset, trans);
    return trans;
  }

  /** 
   * Unpacks the compressed DFA transition table.
   *
   * @param packed   the packed transition table
   * @return         the index of the last entry
   */
  private static int yy_unpack(String packed, int offset, int [] trans) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do trans[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] yy_unpack_cmap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 144) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   IOException  if any I/O-Error occurs
   */
  private boolean yy_refill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (yy_startRead > 0) {
      System.arraycopy(yy_buffer, yy_startRead, 
                       yy_buffer, 0, 
                       yy_endRead-yy_startRead);

      /* translate stored positions */
      yy_endRead-= yy_startRead;
      yy_currentPos-= yy_startRead;
      yy_markedPos-= yy_startRead;
      yy_pushbackPos-= yy_startRead;
      yy_startRead = 0;
    }

    /* is the buffer big enough? */
    if (yy_currentPos >= yy_buffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[yy_currentPos*2];
      System.arraycopy(yy_buffer, 0, newBuffer, 0, yy_buffer.length);
      yy_buffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = yy_reader.read(yy_buffer, yy_endRead, 
                                            yy_buffer.length-yy_endRead);

    if (numRead < 0) {
      return true;
    }
    else {
      yy_endRead+= numRead;  
      return false;
    }
  }


  /**
   * Closes the input stream.
   */
  final public void yyclose() throws java.io.IOException {
    yy_atEOF = true;            /* indicate end of file */
    yy_endRead = yy_startRead;  /* invalidate buffer    */

    if (yy_reader != null)
      yy_reader.close();
  }


  /**
   * Closes the current stream, and resets the
   * scanner to read from a new input stream.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>YY_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  final public void yyreset(java.io.Reader reader) throws java.io.IOException {
    yyclose();
    yy_reader = reader;
    yy_atBOL  = true;
    yy_atEOF  = false;
    yy_endRead = yy_startRead = 0;
    yy_currentPos = yy_markedPos = yy_pushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    yy_lexical_state = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  final public int yystate() {
    return yy_lexical_state;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  final public void yybegin(int newState) {
    yy_lexical_state = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  final public String yytext() {
    return new String( yy_buffer, yy_startRead, yy_markedPos-yy_startRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  final public char yycharat(int pos) {
    return yy_buffer[yy_startRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  final public int yylength() {
    return yy_markedPos-yy_startRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void yy_ScanError(int errorCode) {
    String message;
    try {
      message = YY_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = YY_ERROR_MSG[YY_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  private void yypushback(int number)  {
    if ( number > yylength() )
      yy_ScanError(YY_PUSHBACK_2BIG);

    yy_markedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void yy_do_eof() throws java.io.IOException {
    if (!yy_eof_done) {
      yy_eof_done = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int yy_input;
    int yy_action;

    // cached fields:
    int yy_currentPos_l;
    int yy_startRead_l;
    int yy_markedPos_l;
    int yy_endRead_l = yy_endRead;
    char [] yy_buffer_l = yy_buffer;
    char [] yycmap_l = yycmap;

    int [] yytrans_l = yytrans;
    int [] yy_rowMap_l = yy_rowMap;
    byte [] yy_attr_l = YY_ATTRIBUTE;

    while (true) {
      yy_markedPos_l = yy_markedPos;

      yychar+= yy_markedPos_l-yy_startRead;

      boolean yy_r = false;
      for (yy_currentPos_l = yy_startRead; yy_currentPos_l < yy_markedPos_l;
                                                             yy_currentPos_l++) {
        switch (yy_buffer_l[yy_currentPos_l]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          yy_r = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          yy_r = true;
          break;
        case '\n':
          if (yy_r)
            yy_r = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          yy_r = false;
          yycolumn++;
        }
      }

      if (yy_r) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean yy_peek;
        if (yy_markedPos_l < yy_endRead_l)
          yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        else if (yy_atEOF)
          yy_peek = false;
        else {
          boolean eof = yy_refill();
          yy_markedPos_l = yy_markedPos;
          yy_buffer_l = yy_buffer;
          if (eof) 
            yy_peek = false;
          else 
            yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        }
        if (yy_peek) yyline--;
      }
      yy_action = -1;

      yy_startRead_l = yy_currentPos_l = yy_currentPos = 
                       yy_startRead = yy_markedPos_l;

      yy_state = yy_lexical_state;


      yy_forAction: {
        while (true) {

          if (yy_currentPos_l < yy_endRead_l)
            yy_input = yy_buffer_l[yy_currentPos_l++];
          else if (yy_atEOF) {
            yy_input = YYEOF;
            break yy_forAction;
          }
          else {
            // store back cached positions
            yy_currentPos  = yy_currentPos_l;
            yy_markedPos   = yy_markedPos_l;
            boolean eof = yy_refill();
            // get translated positions and possibly new buffer
            yy_currentPos_l  = yy_currentPos;
            yy_markedPos_l   = yy_markedPos;
            yy_buffer_l      = yy_buffer;
            yy_endRead_l     = yy_endRead;
            if (eof) {
              yy_input = YYEOF;
              break yy_forAction;
            }
            else {
              yy_input = yy_buffer_l[yy_currentPos_l++];
            }
          }
          int yy_next = yytrans_l[ yy_rowMap_l[yy_state] + yycmap_l[yy_input] ];
          if (yy_next == -1) break yy_forAction;
          yy_state = yy_next;

          int yy_attributes = yy_attr_l[yy_state];
          if ( (yy_attributes & 1) == 1 ) {
            yy_action = yy_state; 
            yy_markedPos_l = yy_currentPos_l; 
            if ( (yy_attributes & 8) == 8 ) break yy_forAction;
          }

        }
      }

      // store back cached position
      yy_markedPos = yy_markedPos_l;

      switch (yy_action) {

        case 19: 
          {  return symbol("NOT", NOT);  }
        case 139: break;
        case 5: 
          {  return symbol("DIV", DIV);  }
        case 140: break;
        case 11: 
          {  return symbol("DOT", DOT);  }
        case 141: break;
        case 51: 
          {  return symbol("AND", AND);  }
        case 142: break;
        case 80: 
          {  return symbol("FOR", FOR);  }
        case 143: break;
        case 84: 
          {  return symbol("VAR", VAR);  }
        case 144: break;
        case 107: 
          {  return symbol("CASE", CASE);  }
        case 145: break;
        case 23: 
          {  return symbol("RPAR", RPAR);  }
        case 146: break;
        case 22: 
          {  return symbol("LPAR", LPAR);  }
        case 147: break;
        case 17: 
          {  return symbol("PLUS", PLUS);  }
        case 148: break;
        case 6: 
          {  return symbol("MULT", MULT);  }
        case 149: break;
        case 91: 
          {  return symbol("ELSE", ELSE);  }
        case 150: break;
        case 93: 
          {  return symbol("TYPE", TYPE);  }
        case 151: break;
        case 101: 
          {  return symbol("FUNC", FUNC);  }
        case 152: break;
        case 3: 
        case 4: 
        case 38: 
          {   }
        case 153: break;
        case 112: 
          {  return symbol("EQ", EQ);  }
        case 154: break;
        case 24: 
          {  return symbol("LT", LT);  }
        case 155: break;
        case 7: 
        case 9: 
        case 10: 
        case 13: 
        case 14: 
        case 15: 
        case 16: 
        case 32: 
        case 33: 
        case 34: 
        case 35: 
        case 36: 
        case 37: 
        case 42: 
        case 43: 
        case 44: 
        case 46: 
        case 47: 
        case 48: 
        case 49: 
        case 50: 
        case 54: 
        case 55: 
        case 57: 
        case 58: 
        case 59: 
        case 60: 
        case 61: 
        case 62: 
        case 63: 
        case 64: 
        case 68: 
        case 69: 
        case 70: 
        case 72: 
        case 73: 
        case 74: 
        case 75: 
        case 76: 
        case 78: 
        case 81: 
        case 82: 
        case 83: 
        case 85: 
        case 86: 
        case 87: 
        case 95: 
        case 96: 
        case 97: 
        case 100: 
        case 102: 
        case 103: 
        case 104: 
        case 105: 
        case 106: 
        case 109: 
        case 110: 
        case 111: 
        case 113: 
        case 114: 
        case 117: 
        case 123: 
        case 124: 
        case 125: 
        case 127: 
        case 128: 
        case 131: 
        case 132: 
        case 135: 
        case 136: 
          {  return symbol("ID", ID);  }
        case 156: break;
        case 56: 
          {  return symbol("IF", IF);  }
        case 157: break;
        case 2: 
        case 18: 
        case 20: 
          {  emit_warning("Caracter não reconhecido '" + yytext() + "' -- ignorado");  }
        case 158: break;
        case 8: 
          {  return symbol("INT_NUMBER", INT_NUMBER, new Integer(yytext()));  }
        case 159: break;
        case 122: 
          {  return symbol("SWITCH", SWITCH);  }
        case 160: break;
        case 92: 
          {  return symbol("TRUE", TRUE, true);  }
        case 161: break;
        case 121: 
          {  return symbol("STRUCT", STRUCT);  }
        case 162: break;
        case 115: 
          {  return symbol("FALSE", FALSE, false);  }
        case 163: break;
        case 21: 
          {  return symbol("ASSIGN", ASSIGN);  }
        case 164: break;
        case 53: 
          {  return symbol("DASSIGN", DASSIGN);  }
        case 165: break;
        case 137: 
          {  return symbol("FALLTHROUGH", FALLTHROUGH);  }
        case 166: break;
        case 134: 
          {  return symbol("INTERFACE", INTERFACE);  }
        case 167: break;
        case 116: 
          {  return symbol("FLOAT64", FLOAT64);  }
        case 168: break;
        case 41: 
        case 89: 
        case 130: 
        case 133: 
          {  return symbol("FLOAT_NUMBER", FLOAT_NUMBER, new Float(yytext()));  }
        case 169: break;
        case 71: 
          {  return symbol("DOTDOTDOT", DOTDOTDOT);  }
        case 170: break;
        case 99: 
          {  return symbol("BOOLEAN", BOOLEAN);  }
        case 171: break;
        case 12: 
          {  return symbol("MINUS", MINUS);  }
        case 172: break;
        case 94: 
          {  return symbol("BOOLEAN", BOOLEAN, new Boolean(yytext()));  }
        case 173: break;
        case 79: 
          {  return symbol("INT32", INT32);  }
        case 174: break;
        case 129: 
          {  return symbol("DEFAULT", DEFAULT);  }
        case 175: break;
        case 120: 
          {  return symbol("RETURN", RETURN);  }
        case 176: break;
        case 118: 
          {  return symbol("CONST", CONST);  }
        case 177: break;
        case 29: 
          {  return symbol("COLON", COLON);  }
        case 178: break;
        case 30: 
          {  return symbol("COMMA", COMMA);  }
        case 179: break;
        case 31: 
          {  return symbol("SEMICOLON", SEMICOLON);  }
        case 180: break;
        case 27: 
          {  return symbol("LBRACK", LBRACK);  }
        case 181: break;
        case 26: 
          {  return symbol("RSBRACK", RSBRACK);  }
        case 182: break;
        case 25: 
          {  return symbol("LSBRACK", LSBRACK);  }
        case 183: break;
        case 28: 
          {  return symbol("RBRACK", RBRACK);  }
        case 184: break;
        default: 
          if (yy_input == YYEOF && yy_startRead == yy_currentPos) {
            yy_atEOF = true;
            yy_do_eof();
              {     return symbolFactory.newSymbol("EOF",sym.EOF);
 }
          } 
          else {
            yy_ScanError(YY_NO_MATCH);
          }
      }
    }
  }


}
