
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package pasito.syntax;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int MULT = 28;
  public static final int CONST = 13;
  public static final int INT32 = 21;
  public static final int CASE = 7;
  public static final int INTERFACE = 5;
  public static final int FOR = 15;
  public static final int MINUS = 27;
  public static final int SEMICOLON = 43;
  public static final int NOT = 33;
  public static final int AND = 30;
  public static final int RANGE = 17;
  public static final int LT = 32;
  public static final int RPAR = 35;
  public static final int TYPE = 9;
  public static final int COMMA = 42;
  public static final int DIV = 29;
  public static final int FLOAT_NUMBER = 25;
  public static final int DIGIT = 23;
  public static final int PLUS = 26;
  public static final int ASSIGN = 40;
  public static final int LSBRACK = 36;
  public static final int IF = 12;
  public static final int DOT = 46;
  public static final int ID = 2;
  public static final int RSBRACK = 37;
  public static final int EOF = 0;
  public static final int BOOLEAN = 18;
  public static final int RETURN = 16;
  public static final int TRUE = 19;
  public static final int error = 1;
  public static final int FLOAT64 = 22;
  public static final int EQ = 31;
  public static final int DASSIGN = 41;
  public static final int LBRACK = 38;
  public static final int SWITCH = 11;
  public static final int COLON = 45;
  public static final int ELSE = 10;
  public static final int FUNC = 4;
  public static final int RBRACK = 39;
  public static final int DOTDOTDOT = 44;
  public static final int DEFAULT = 3;
  public static final int INT_NUMBER = 24;
  public static final int LPAR = 34;
  public static final int FALSE = 20;
  public static final int STRUCT = 8;
  public static final int VAR = 14;
  public static final int FALLTHROUGH = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "DEFAULT",
  "FUNC",
  "INTERFACE",
  "FALLTHROUGH",
  "CASE",
  "STRUCT",
  "TYPE",
  "ELSE",
  "SWITCH",
  "IF",
  "CONST",
  "VAR",
  "FOR",
  "RETURN",
  "RANGE",
  "BOOLEAN",
  "TRUE",
  "FALSE",
  "INT32",
  "FLOAT64",
  "DIGIT",
  "INT_NUMBER",
  "FLOAT_NUMBER",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "AND",
  "EQ",
  "LT",
  "NOT",
  "LPAR",
  "RPAR",
  "LSBRACK",
  "RSBRACK",
  "LBRACK",
  "RBRACK",
  "ASSIGN",
  "DASSIGN",
  "COMMA",
  "SEMICOLON",
  "DOTDOTDOT",
  "COLON",
  "DOT"
  };
}

